import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { Routes } from "../constants/routes"
import buttonsStyles from "../styles/buttons.module.scss"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ventura HR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <h2 className={buttonsStyles.buttonSetHeader}>Cadastre-se</h2>

          <div className={buttonsStyles.buttonsSet}>
            <Link href={Routes.CompaniesSignup}>
              <button className={buttonsStyles.button}>
                Cadastrar Empresa
              </button>
            </Link>

            <Link href={Routes.ApplicantsSignup}>
              <button className={buttonsStyles.button}>
                Cadastrar Candidato
              </button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
