version: "3.9"

services:
  api_gateway:
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - venturahr_net
    depends_on:
      - jobposting
  jobposting:
    build:
      context: ./Services/JobPostings
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
    depends_on:
      - jobposting_db
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - venturahr_net
  jobposting_db:
    image: postgres
    restart: always
    networks:
      - venturahr_net
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - venturahr_net

networks:
  venturahr_net: