//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPostings.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobPostings.CrossCutting.Resources.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vaga {0} expirou há mais de {1} dias e não foi renovada, portanto foi fechada..
        /// </summary>
        public static string ClosedJobBody {
            get {
                return ResourceManager.GetString("ClosedJobBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaga fechada.
        /// </summary>
        public static string ClosedJobTitle {
            get {
                return ResourceManager.GetString("ClosedJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vaga {0} expirou..
        /// </summary>
        public static string ExpiredJobBody {
            get {
                return ResourceManager.GetString("ExpiredJobBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaga expirada.
        /// </summary>
        public static string ExpiredJobTitle {
            get {
                return ResourceManager.GetString("ExpiredJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vaga {0} está prevista para expirar em {1}..
        /// </summary>
        public static string ExpiringJobBody {
            get {
                return ResourceManager.GetString("ExpiringJobBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaga prestes à expirar.
        /// </summary>
        public static string ExpiringJobTitle {
            get {
                return ResourceManager.GetString("ExpiringJobTitle", resourceCulture);
            }
        }
    }
}
