// <auto-generated />
using System;
using JobPostings.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobPostings.Infra.Data.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20220525032943_RemoveJobPostingColumns")]
    partial class RemoveJobPostingColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobPostings.Domain.Aggregates.Applicants.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Applicants", (string)null);
                });

            modelBuilder.Entity("JobPostings.Domain.Aggregates.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("JobPostings.Domain.Aggregates.JobApplications.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("_applicantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("_jobPostingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("_applicantId");

                    b.HasIndex("_jobPostingId");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("JobPostings.Domain.Aggregates.JobPostings.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("_companyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("_companyId");

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("JobPostings.Domain.Aggregates.JobApplications.JobApplication", b =>
                {
                    b.HasOne("JobPostings.Domain.Aggregates.Applicants.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("_applicantId");

                    b.HasOne("JobPostings.Domain.Aggregates.JobPostings.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("_jobPostingId");

                    b.Navigation("Applicant");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobPostings.Domain.Aggregates.JobPostings.JobPosting", b =>
                {
                    b.HasOne("JobPostings.Domain.Aggregates.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("_companyId");

                    b.OwnsOne("JobPostings.Domain.Aggregates.JobPostings.Salary", "Salary", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Compensation");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.Navigation("Company");

                    b.Navigation("Salary");
                });
#pragma warning restore 612, 618
        }
    }
}
