// <auto-generated />


#nullable disable

using System;
using JobPostings.Infra.Data;
using JobPostings.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
namespace JobPostings.Infra.Data.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20220525000514_ChangeJobPostingRoleToJobTitle")]
    partial class ChangeJobPostingRoleToJobTitle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobPostings.Domain.Aggregates.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("JobPostings.Domain.Aggregates.JobPostings.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("_companyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("_companyId");

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("JobPostings.Domain.Aggregates.JobPostings.JobPosting", b =>
                {
                    b.HasOne("JobPostings.Domain.Aggregates.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("_companyId");

                    b.OwnsOne("JobPostings.Domain.Aggregates.JobPostings.ExpirationDate", "ExpireAt", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ExpireAt");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPostings.Domain.Aggregates.JobPostings.JobTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Title");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPostings.Domain.Aggregates.JobPostings.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Place")
                                .HasColumnType("text")
                                .HasColumnName("Location");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPostings.Domain.Aggregates.JobPostings.Salary", "Salary", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Compensation");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.Navigation("Company");

                    b.Navigation("ExpireAt");

                    b.Navigation("Location");

                    b.Navigation("Salary");

                    b.Navigation("Title");
                });
#pragma warning restore 612, 618
        }
    }
}
