// <auto-generated />
using System;
using JobPostings.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobPostings.Infra.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20220515215803_RemoveCompaniesTable")]
    partial class RemoveCompaniesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobPostings.Domain.JobPostingAggregate.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobPostings", (string)null);
                });

            modelBuilder.Entity("JobPostings.Domain.JobPostingAggregate.JobPosting", b =>
                {
                    b.OwnsOne("JobPostings.Domain.JobPostingAggregate.CompanyId", "CompanyId", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("CompanyId");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPostings.Domain.JobPostingAggregate.ExpirationDate", "ExpireAt", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ExpireAt");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPostings.Domain.JobPostingAggregate.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Place")
                                .HasColumnType("text")
                                .HasColumnName("Location");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.OwnsOne("JobPostings.Domain.JobPostingAggregate.Salary", "Salary", b1 =>
                        {
                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Compensation");

                            b1.HasKey("JobPostingId");

                            b1.ToTable("JobPostings");

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId");
                        });

                    b.Navigation("CompanyId");

                    b.Navigation("ExpireAt");

                    b.Navigation("Location");

                    b.Navigation("Salary");
                });
#pragma warning restore 612, 618
        }
    }
}
