name: ApiGatewayDeploy

on:
  push:
    branches: [ main ]
    paths:
      - ApiGateway/**
  pull_request:
    branches: [ main ]


  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

defaults:
  run:
    working-directory: ApiGateway

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Heroku Container registry
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a venturahr-api-gateway web
      - name: Release
        run:  heroku container:release -a venturahr-api-gateway web
