name: ApiGatewayDeploy

on:
  push:
    branches: [ main ]
    paths:
      - ApiGateway/**
  pull_request:
    branches: [ main ]


  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

defaults:
  run:
    working-directory: ApiGateway

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0
        with:
          heroku_email: "fabiopereira.fps@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "venturahr-api-gateway"
          buildpacks: "['https://github.com/atirson/heroku-buildpack-krakend-easy']"
