name: CommonDeploy

on:
  push:
    branches: [ main ]
    paths:
      - SharedKernel/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: dotnet pack -c Release -o . SharedKernel/Common/Common.csproj
      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
