# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

defaults:
  run:
    working-directory: Services/JobPostings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Heroku Container registry
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a venturahr-job-postings web
      - name: Release
        run:  heroku container:release -a venturahr-job-postings web
