name: JobPostingsDeploy

on:
  push:
    branches: [ main ]
    paths:
      - Services/Users/**

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  DIR_PATH: Services/Users

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Login to Heroku Container registry
        run: heroku container:login
        working-directory: ${{ env.DIR_PATH }}
      - name: Build and push
        run: heroku container:push -a venturahr-job-postings web
        working-directory: ${{ env.DIR_PATH }}
      - name: Release
        run: heroku container:release -a venturahr-job-postings web
        working-directory: ${{ env.DIR_PATH }}
